# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jtv/sdl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jtv/sdl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtv/sdl/CMakeFiles /home/jtv/sdl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtv/sdl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mac

# Build rule for target.
mac: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mac
.PHONY : mac

# fast build rule for target.
mac/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/build
.PHONY : mac/fast

src/game/player/player.o: src/game/player/player.cpp.o
.PHONY : src/game/player/player.o

# target to build an object file
src/game/player/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player.cpp.o
.PHONY : src/game/player/player.cpp.o

src/game/player/player.i: src/game/player/player.cpp.i
.PHONY : src/game/player/player.i

# target to preprocess a source file
src/game/player/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player.cpp.i
.PHONY : src/game/player/player.cpp.i

src/game/player/player.s: src/game/player/player.cpp.s
.PHONY : src/game/player/player.s

# target to generate assembly for a file
src/game/player/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player.cpp.s
.PHONY : src/game/player/player.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/manager/game_state.o: src/manager/game_state.cpp.o
.PHONY : src/manager/game_state.o

# target to build an object file
src/manager/game_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/game_state.cpp.o
.PHONY : src/manager/game_state.cpp.o

src/manager/game_state.i: src/manager/game_state.cpp.i
.PHONY : src/manager/game_state.i

# target to preprocess a source file
src/manager/game_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/game_state.cpp.i
.PHONY : src/manager/game_state.cpp.i

src/manager/game_state.s: src/manager/game_state.cpp.s
.PHONY : src/manager/game_state.s

# target to generate assembly for a file
src/manager/game_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/game_state.cpp.s
.PHONY : src/manager/game_state.cpp.s

src/manager/process/process.o: src/manager/process/process.cpp.o
.PHONY : src/manager/process/process.o

# target to build an object file
src/manager/process/process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process.cpp.o
.PHONY : src/manager/process/process.cpp.o

src/manager/process/process.i: src/manager/process/process.cpp.i
.PHONY : src/manager/process/process.i

# target to preprocess a source file
src/manager/process/process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process.cpp.i
.PHONY : src/manager/process/process.cpp.i

src/manager/process/process.s: src/manager/process/process.cpp.s
.PHONY : src/manager/process/process.s

# target to generate assembly for a file
src/manager/process/process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process.cpp.s
.PHONY : src/manager/process/process.cpp.s

src/manager/process/process_manager.o: src/manager/process/process_manager.cpp.o
.PHONY : src/manager/process/process_manager.o

# target to build an object file
src/manager/process/process_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process_manager.cpp.o
.PHONY : src/manager/process/process_manager.cpp.o

src/manager/process/process_manager.i: src/manager/process/process_manager.cpp.i
.PHONY : src/manager/process/process_manager.i

# target to preprocess a source file
src/manager/process/process_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process_manager.cpp.i
.PHONY : src/manager/process/process_manager.cpp.i

src/manager/process/process_manager.s: src/manager/process/process_manager.cpp.s
.PHONY : src/manager/process/process_manager.s

# target to generate assembly for a file
src/manager/process/process_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process_manager.cpp.s
.PHONY : src/manager/process/process_manager.cpp.s

src/renderer/renderer.o: src/renderer/renderer.cpp.o
.PHONY : src/renderer/renderer.o

# target to build an object file
src/renderer/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/renderer.cpp.o
.PHONY : src/renderer/renderer.cpp.o

src/renderer/renderer.i: src/renderer/renderer.cpp.i
.PHONY : src/renderer/renderer.i

# target to preprocess a source file
src/renderer/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/renderer.cpp.i
.PHONY : src/renderer/renderer.cpp.i

src/renderer/renderer.s: src/renderer/renderer.cpp.s
.PHONY : src/renderer/renderer.s

# target to generate assembly for a file
src/renderer/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/renderer.cpp.s
.PHONY : src/renderer/renderer.cpp.s

src/texture/texture.o: src/texture/texture.cpp.o
.PHONY : src/texture/texture.o

# target to build an object file
src/texture/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/texture/texture.cpp.o
.PHONY : src/texture/texture.cpp.o

src/texture/texture.i: src/texture/texture.cpp.i
.PHONY : src/texture/texture.i

# target to preprocess a source file
src/texture/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/texture/texture.cpp.i
.PHONY : src/texture/texture.cpp.i

src/texture/texture.s: src/texture/texture.cpp.s
.PHONY : src/texture/texture.s

# target to generate assembly for a file
src/texture/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/texture/texture.cpp.s
.PHONY : src/texture/texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mac"
	@echo "... src/game/player/player.o"
	@echo "... src/game/player/player.i"
	@echo "... src/game/player/player.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/manager/game_state.o"
	@echo "... src/manager/game_state.i"
	@echo "... src/manager/game_state.s"
	@echo "... src/manager/process/process.o"
	@echo "... src/manager/process/process.i"
	@echo "... src/manager/process/process.s"
	@echo "... src/manager/process/process_manager.o"
	@echo "... src/manager/process/process_manager.i"
	@echo "... src/manager/process/process_manager.s"
	@echo "... src/renderer/renderer.o"
	@echo "... src/renderer/renderer.i"
	@echo "... src/renderer/renderer.s"
	@echo "... src/texture/texture.o"
	@echo "... src/texture/texture.i"
	@echo "... src/texture/texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

