# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jtv/Macaroni-pirates

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jtv/Macaroni-pirates

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtv/Macaroni-pirates/CMakeFiles /home/jtv/Macaroni-pirates//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtv/Macaroni-pirates/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/jtv/Macaroni-pirates/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mac

# Build rule for target.
mac: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mac
.PHONY : mac

# fast build rule for target.
mac/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/build
.PHONY : mac/fast

src/game/ally/ally.o: src/game/ally/ally.cpp.o
.PHONY : src/game/ally/ally.o

# target to build an object file
src/game/ally/ally.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/ally/ally.cpp.o
.PHONY : src/game/ally/ally.cpp.o

src/game/ally/ally.i: src/game/ally/ally.cpp.i
.PHONY : src/game/ally/ally.i

# target to preprocess a source file
src/game/ally/ally.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/ally/ally.cpp.i
.PHONY : src/game/ally/ally.cpp.i

src/game/ally/ally.s: src/game/ally/ally.cpp.s
.PHONY : src/game/ally/ally.s

# target to generate assembly for a file
src/game/ally/ally.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/ally/ally.cpp.s
.PHONY : src/game/ally/ally.cpp.s

src/game/enemy/enemy.o: src/game/enemy/enemy.cpp.o
.PHONY : src/game/enemy/enemy.o

# target to build an object file
src/game/enemy/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/enemy/enemy.cpp.o
.PHONY : src/game/enemy/enemy.cpp.o

src/game/enemy/enemy.i: src/game/enemy/enemy.cpp.i
.PHONY : src/game/enemy/enemy.i

# target to preprocess a source file
src/game/enemy/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/enemy/enemy.cpp.i
.PHONY : src/game/enemy/enemy.cpp.i

src/game/enemy/enemy.s: src/game/enemy/enemy.cpp.s
.PHONY : src/game/enemy/enemy.s

# target to generate assembly for a file
src/game/enemy/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/enemy/enemy.cpp.s
.PHONY : src/game/enemy/enemy.cpp.s

src/game/map/map.o: src/game/map/map.cpp.o
.PHONY : src/game/map/map.o

# target to build an object file
src/game/map/map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/map/map.cpp.o
.PHONY : src/game/map/map.cpp.o

src/game/map/map.i: src/game/map/map.cpp.i
.PHONY : src/game/map/map.i

# target to preprocess a source file
src/game/map/map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/map/map.cpp.i
.PHONY : src/game/map/map.cpp.i

src/game/map/map.s: src/game/map/map.cpp.s
.PHONY : src/game/map/map.s

# target to generate assembly for a file
src/game/map/map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/map/map.cpp.s
.PHONY : src/game/map/map.cpp.s

src/game/player/cannonball/cannonball.o: src/game/player/cannonball/cannonball.cpp.o
.PHONY : src/game/player/cannonball/cannonball.o

# target to build an object file
src/game/player/cannonball/cannonball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/cannonball/cannonball.cpp.o
.PHONY : src/game/player/cannonball/cannonball.cpp.o

src/game/player/cannonball/cannonball.i: src/game/player/cannonball/cannonball.cpp.i
.PHONY : src/game/player/cannonball/cannonball.i

# target to preprocess a source file
src/game/player/cannonball/cannonball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/cannonball/cannonball.cpp.i
.PHONY : src/game/player/cannonball/cannonball.cpp.i

src/game/player/cannonball/cannonball.s: src/game/player/cannonball/cannonball.cpp.s
.PHONY : src/game/player/cannonball/cannonball.s

# target to generate assembly for a file
src/game/player/cannonball/cannonball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/cannonball/cannonball.cpp.s
.PHONY : src/game/player/cannonball/cannonball.cpp.s

src/game/player/player.o: src/game/player/player.cpp.o
.PHONY : src/game/player/player.o

# target to build an object file
src/game/player/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player.cpp.o
.PHONY : src/game/player/player.cpp.o

src/game/player/player.i: src/game/player/player.cpp.i
.PHONY : src/game/player/player.i

# target to preprocess a source file
src/game/player/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player.cpp.i
.PHONY : src/game/player/player.cpp.i

src/game/player/player.s: src/game/player/player.cpp.s
.PHONY : src/game/player/player.s

# target to generate assembly for a file
src/game/player/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player.cpp.s
.PHONY : src/game/player/player.cpp.s

src/game/player/player_replay.o: src/game/player/player_replay.cpp.o
.PHONY : src/game/player/player_replay.o

# target to build an object file
src/game/player/player_replay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player_replay.cpp.o
.PHONY : src/game/player/player_replay.cpp.o

src/game/player/player_replay.i: src/game/player/player_replay.cpp.i
.PHONY : src/game/player/player_replay.i

# target to preprocess a source file
src/game/player/player_replay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player_replay.cpp.i
.PHONY : src/game/player/player_replay.cpp.i

src/game/player/player_replay.s: src/game/player/player_replay.cpp.s
.PHONY : src/game/player/player_replay.s

# target to generate assembly for a file
src/game/player/player_replay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/player/player_replay.cpp.s
.PHONY : src/game/player/player_replay.cpp.s

src/game/score_store.o: src/game/score_store.cpp.o
.PHONY : src/game/score_store.o

# target to build an object file
src/game/score_store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/score_store.cpp.o
.PHONY : src/game/score_store.cpp.o

src/game/score_store.i: src/game/score_store.cpp.i
.PHONY : src/game/score_store.i

# target to preprocess a source file
src/game/score_store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/score_store.cpp.i
.PHONY : src/game/score_store.cpp.i

src/game/score_store.s: src/game/score_store.cpp.s
.PHONY : src/game/score_store.s

# target to generate assembly for a file
src/game/score_store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/game/score_store.cpp.s
.PHONY : src/game/score_store.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/manager/game_state.o: src/manager/game_state.cpp.o
.PHONY : src/manager/game_state.o

# target to build an object file
src/manager/game_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/game_state.cpp.o
.PHONY : src/manager/game_state.cpp.o

src/manager/game_state.i: src/manager/game_state.cpp.i
.PHONY : src/manager/game_state.i

# target to preprocess a source file
src/manager/game_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/game_state.cpp.i
.PHONY : src/manager/game_state.cpp.i

src/manager/game_state.s: src/manager/game_state.cpp.s
.PHONY : src/manager/game_state.s

# target to generate assembly for a file
src/manager/game_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/game_state.cpp.s
.PHONY : src/manager/game_state.cpp.s

src/manager/process/process.o: src/manager/process/process.cpp.o
.PHONY : src/manager/process/process.o

# target to build an object file
src/manager/process/process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process.cpp.o
.PHONY : src/manager/process/process.cpp.o

src/manager/process/process.i: src/manager/process/process.cpp.i
.PHONY : src/manager/process/process.i

# target to preprocess a source file
src/manager/process/process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process.cpp.i
.PHONY : src/manager/process/process.cpp.i

src/manager/process/process.s: src/manager/process/process.cpp.s
.PHONY : src/manager/process/process.s

# target to generate assembly for a file
src/manager/process/process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process.cpp.s
.PHONY : src/manager/process/process.cpp.s

src/manager/process/process_manager.o: src/manager/process/process_manager.cpp.o
.PHONY : src/manager/process/process_manager.o

# target to build an object file
src/manager/process/process_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process_manager.cpp.o
.PHONY : src/manager/process/process_manager.cpp.o

src/manager/process/process_manager.i: src/manager/process/process_manager.cpp.i
.PHONY : src/manager/process/process_manager.i

# target to preprocess a source file
src/manager/process/process_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process_manager.cpp.i
.PHONY : src/manager/process/process_manager.cpp.i

src/manager/process/process_manager.s: src/manager/process/process_manager.cpp.s
.PHONY : src/manager/process/process_manager.s

# target to generate assembly for a file
src/manager/process/process_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/manager/process/process_manager.cpp.s
.PHONY : src/manager/process/process_manager.cpp.s

src/renderer/drawable/drawable.o: src/renderer/drawable/drawable.cpp.o
.PHONY : src/renderer/drawable/drawable.o

# target to build an object file
src/renderer/drawable/drawable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/drawable/drawable.cpp.o
.PHONY : src/renderer/drawable/drawable.cpp.o

src/renderer/drawable/drawable.i: src/renderer/drawable/drawable.cpp.i
.PHONY : src/renderer/drawable/drawable.i

# target to preprocess a source file
src/renderer/drawable/drawable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/drawable/drawable.cpp.i
.PHONY : src/renderer/drawable/drawable.cpp.i

src/renderer/drawable/drawable.s: src/renderer/drawable/drawable.cpp.s
.PHONY : src/renderer/drawable/drawable.s

# target to generate assembly for a file
src/renderer/drawable/drawable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/drawable/drawable.cpp.s
.PHONY : src/renderer/drawable/drawable.cpp.s

src/renderer/font/font_renderer.o: src/renderer/font/font_renderer.cpp.o
.PHONY : src/renderer/font/font_renderer.o

# target to build an object file
src/renderer/font/font_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/font/font_renderer.cpp.o
.PHONY : src/renderer/font/font_renderer.cpp.o

src/renderer/font/font_renderer.i: src/renderer/font/font_renderer.cpp.i
.PHONY : src/renderer/font/font_renderer.i

# target to preprocess a source file
src/renderer/font/font_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/font/font_renderer.cpp.i
.PHONY : src/renderer/font/font_renderer.cpp.i

src/renderer/font/font_renderer.s: src/renderer/font/font_renderer.cpp.s
.PHONY : src/renderer/font/font_renderer.s

# target to generate assembly for a file
src/renderer/font/font_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/font/font_renderer.cpp.s
.PHONY : src/renderer/font/font_renderer.cpp.s

src/renderer/renderer.o: src/renderer/renderer.cpp.o
.PHONY : src/renderer/renderer.o

# target to build an object file
src/renderer/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/renderer.cpp.o
.PHONY : src/renderer/renderer.cpp.o

src/renderer/renderer.i: src/renderer/renderer.cpp.i
.PHONY : src/renderer/renderer.i

# target to preprocess a source file
src/renderer/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/renderer.cpp.i
.PHONY : src/renderer/renderer.cpp.i

src/renderer/renderer.s: src/renderer/renderer.cpp.s
.PHONY : src/renderer/renderer.s

# target to generate assembly for a file
src/renderer/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/renderer/renderer.cpp.s
.PHONY : src/renderer/renderer.cpp.s

src/texture/texture.o: src/texture/texture.cpp.o
.PHONY : src/texture/texture.o

# target to build an object file
src/texture/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/texture/texture.cpp.o
.PHONY : src/texture/texture.cpp.o

src/texture/texture.i: src/texture/texture.cpp.i
.PHONY : src/texture/texture.i

# target to preprocess a source file
src/texture/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/texture/texture.cpp.i
.PHONY : src/texture/texture.cpp.i

src/texture/texture.s: src/texture/texture.cpp.s
.PHONY : src/texture/texture.s

# target to generate assembly for a file
src/texture/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/texture/texture.cpp.s
.PHONY : src/texture/texture.cpp.s

src/ui/game_ui.o: src/ui/game_ui.cpp.o
.PHONY : src/ui/game_ui.o

# target to build an object file
src/ui/game_ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/game_ui.cpp.o
.PHONY : src/ui/game_ui.cpp.o

src/ui/game_ui.i: src/ui/game_ui.cpp.i
.PHONY : src/ui/game_ui.i

# target to preprocess a source file
src/ui/game_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/game_ui.cpp.i
.PHONY : src/ui/game_ui.cpp.i

src/ui/game_ui.s: src/ui/game_ui.cpp.s
.PHONY : src/ui/game_ui.s

# target to generate assembly for a file
src/ui/game_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/game_ui.cpp.s
.PHONY : src/ui/game_ui.cpp.s

src/ui/main_menu.o: src/ui/main_menu.cpp.o
.PHONY : src/ui/main_menu.o

# target to build an object file
src/ui/main_menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/main_menu.cpp.o
.PHONY : src/ui/main_menu.cpp.o

src/ui/main_menu.i: src/ui/main_menu.cpp.i
.PHONY : src/ui/main_menu.i

# target to preprocess a source file
src/ui/main_menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/main_menu.cpp.i
.PHONY : src/ui/main_menu.cpp.i

src/ui/main_menu.s: src/ui/main_menu.cpp.s
.PHONY : src/ui/main_menu.s

# target to generate assembly for a file
src/ui/main_menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/main_menu.cpp.s
.PHONY : src/ui/main_menu.cpp.s

src/ui/pause_menu.o: src/ui/pause_menu.cpp.o
.PHONY : src/ui/pause_menu.o

# target to build an object file
src/ui/pause_menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/pause_menu.cpp.o
.PHONY : src/ui/pause_menu.cpp.o

src/ui/pause_menu.i: src/ui/pause_menu.cpp.i
.PHONY : src/ui/pause_menu.i

# target to preprocess a source file
src/ui/pause_menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/pause_menu.cpp.i
.PHONY : src/ui/pause_menu.cpp.i

src/ui/pause_menu.s: src/ui/pause_menu.cpp.s
.PHONY : src/ui/pause_menu.s

# target to generate assembly for a file
src/ui/pause_menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/pause_menu.cpp.s
.PHONY : src/ui/pause_menu.cpp.s

src/ui/ui_button.o: src/ui/ui_button.cpp.o
.PHONY : src/ui/ui_button.o

# target to build an object file
src/ui/ui_button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/ui_button.cpp.o
.PHONY : src/ui/ui_button.cpp.o

src/ui/ui_button.i: src/ui/ui_button.cpp.i
.PHONY : src/ui/ui_button.i

# target to preprocess a source file
src/ui/ui_button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/ui_button.cpp.i
.PHONY : src/ui/ui_button.cpp.i

src/ui/ui_button.s: src/ui/ui_button.cpp.s
.PHONY : src/ui/ui_button.s

# target to generate assembly for a file
src/ui/ui_button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/ui_button.cpp.s
.PHONY : src/ui/ui_button.cpp.s

src/ui/ui_text_field.o: src/ui/ui_text_field.cpp.o
.PHONY : src/ui/ui_text_field.o

# target to build an object file
src/ui/ui_text_field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/ui_text_field.cpp.o
.PHONY : src/ui/ui_text_field.cpp.o

src/ui/ui_text_field.i: src/ui/ui_text_field.cpp.i
.PHONY : src/ui/ui_text_field.i

# target to preprocess a source file
src/ui/ui_text_field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/ui_text_field.cpp.i
.PHONY : src/ui/ui_text_field.cpp.i

src/ui/ui_text_field.s: src/ui/ui_text_field.cpp.s
.PHONY : src/ui/ui_text_field.s

# target to generate assembly for a file
src/ui/ui_text_field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mac.dir/build.make CMakeFiles/mac.dir/src/ui/ui_text_field.cpp.s
.PHONY : src/ui/ui_text_field.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mac"
	@echo "... src/game/ally/ally.o"
	@echo "... src/game/ally/ally.i"
	@echo "... src/game/ally/ally.s"
	@echo "... src/game/enemy/enemy.o"
	@echo "... src/game/enemy/enemy.i"
	@echo "... src/game/enemy/enemy.s"
	@echo "... src/game/map/map.o"
	@echo "... src/game/map/map.i"
	@echo "... src/game/map/map.s"
	@echo "... src/game/player/cannonball/cannonball.o"
	@echo "... src/game/player/cannonball/cannonball.i"
	@echo "... src/game/player/cannonball/cannonball.s"
	@echo "... src/game/player/player.o"
	@echo "... src/game/player/player.i"
	@echo "... src/game/player/player.s"
	@echo "... src/game/player/player_replay.o"
	@echo "... src/game/player/player_replay.i"
	@echo "... src/game/player/player_replay.s"
	@echo "... src/game/score_store.o"
	@echo "... src/game/score_store.i"
	@echo "... src/game/score_store.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/manager/game_state.o"
	@echo "... src/manager/game_state.i"
	@echo "... src/manager/game_state.s"
	@echo "... src/manager/process/process.o"
	@echo "... src/manager/process/process.i"
	@echo "... src/manager/process/process.s"
	@echo "... src/manager/process/process_manager.o"
	@echo "... src/manager/process/process_manager.i"
	@echo "... src/manager/process/process_manager.s"
	@echo "... src/renderer/drawable/drawable.o"
	@echo "... src/renderer/drawable/drawable.i"
	@echo "... src/renderer/drawable/drawable.s"
	@echo "... src/renderer/font/font_renderer.o"
	@echo "... src/renderer/font/font_renderer.i"
	@echo "... src/renderer/font/font_renderer.s"
	@echo "... src/renderer/renderer.o"
	@echo "... src/renderer/renderer.i"
	@echo "... src/renderer/renderer.s"
	@echo "... src/texture/texture.o"
	@echo "... src/texture/texture.i"
	@echo "... src/texture/texture.s"
	@echo "... src/ui/game_ui.o"
	@echo "... src/ui/game_ui.i"
	@echo "... src/ui/game_ui.s"
	@echo "... src/ui/main_menu.o"
	@echo "... src/ui/main_menu.i"
	@echo "... src/ui/main_menu.s"
	@echo "... src/ui/pause_menu.o"
	@echo "... src/ui/pause_menu.i"
	@echo "... src/ui/pause_menu.s"
	@echo "... src/ui/ui_button.o"
	@echo "... src/ui/ui_button.i"
	@echo "... src/ui/ui_button.s"
	@echo "... src/ui/ui_text_field.o"
	@echo "... src/ui/ui_text_field.i"
	@echo "... src/ui/ui_text_field.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/jtv/Macaroni-pirates/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

